from stacker.optimization.parameters.parameter import Parameter

max_depth = Parameter("max_depth")
learning_rate = Parameter("learning_rate")
n_estimators = Parameter("n_estimators")
objective = Parameter("objective")
gamma = Parameter("gamma")
min_child_weight = Parameter("min_child_weight")
max_delta_step = Parameter("max_delta_step")
subsample = Parameter("subsample")
colsample_bytree = Parameter("colsample_bytree")
colsample_bylevel = Parameter("colsample_bylevel")
reg_alpha = Parameter("reg_alpha")
reg_lambda = Parameter("reg_lambda")
scale_pos_weight = Parameter("scale_pos_weight")
base_score = Parameter("base_score")
